name: MythicLib
author: Indyuce
main: io.lumine.mythic.lib.MythicLib
api-version: 1.14
version: ${project.version}
description: ${project.description}
website: www.phoenixdevt.fr
# AuraSkills must be enabled before initializing API class
softdepend: [ WorldGuard,Residence,MythicMobs,PlaceholderAPI,Fabled,AureliumSkills,AuraSkills,packetevents ]
loadbefore: [ MMOProfiles, MMOCore ]
folia-supported: true
commands:
  mythiclib:
    description: 'Main command for MythicLib'
    permission: 'mythiclib.admin'
    aliases: [ 'ml' ]
permissions:
  mythiclib.admin:
    default: op
  mythiclib.mythiclib.command.healthscale:
    default: op
  mythiclib.tempstat:
    default: op
  mythiclib.superworkbench:
    default: op
  mythiclib.megaworkbench:
    default: op
